server:
  error:
    include-message: never
    include-binding-errors: never

spring:
  datasource:
    password: docker
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true